import {useEffect, useState} from "react";
import axios from "axios";
import ReactMarkdown from 'react-markdown';

const AiCaption = (inputData) => {
    const [caption, setCaption] = useState(null);
    const [acceptedAi, setAcceptedAi] = useState(false);

    const getCaption = async () => {
        try {
            const jwtToken = localStorage.getItem('jwtToken');
            const response = await axios.post(
                'http://localhost:8080/ai/graphCaption',
                {
                    "Starting age of retirement": inputData.initalParameters.retirementAge,
                    "Planned age at end of retirement": (inputData.initalParameters.retirementAge + inputData.initalParameters.numberOfYearsInRetirement),
                    "Initial Retirement Parameters": inputData.initalParameters,
                    "Years of data": inputData.data
                },
                {
                    headers: {
                        Authorization: `Bearer ${jwtToken}`,
                    },
                }
            );
            setCaption(response.data);
        } catch (error) {
            console.error('Error getting caption:', error.response || error.message || error);
            alert('Error getting caption');
        }
    };

    useEffect(() => {
        if (acceptedAi) {
            setCaption(null);
            getCaption();
        }
    }, [inputData.data, acceptedAi]);


    return (
        <div>
            {acceptedAi && caption &&
                <div>
                    <ReactMarkdown>{caption}</ReactMarkdown>
                    <p className="aiDisclosure">This was generated by an AI.</p>
                </div>
            }
            {acceptedAi && !caption &&
                <div>
                    <p>Generating caption.</p>
                </div>
            }
            {!acceptedAi &&
                <div>
                    <p>Please accept AI caption generation</p>
                    <button onClick={() => setAcceptedAi(true)}>Accept</button>
                </div>
            }
        </div>
    );
};

export default AiCaption;
